export const PLAYER = {
  INITIAL_LIFE: 100,
  JUMP_IMPULSE: 16,
  VELOCITY: 28,
  BOOST_FACTOR: 2.5,
  BODY_RADIUS: 0.5,
  BODY_LINEAR_DAMPING: 0.1,
  BODY_ANGULAR_DAMPING: 0.1,
  Y_AXIS: 0.75,
  INIT_POSITION: [0, 30, 10]
};

export const CORONA = {
  ORIENTATION_THRESHOLD: 0.5,
  LIFE: 3,
  Y_AXIS: 1,
  SEEK_ALERT_DURATION: 2000,
  PREATTACK_DURATION: 1000,
  ATTACK_DURATION: 200,
  UNDER_ATTACK_DURATION: 300,
  SPAWN_ANIMATION_DURATION: 3000,
  SPAWN_INTERVAL: 10000,
  BODY_RADIUS: 0.5,
  IDLE_VELOCITY: 1 / 50,
  SEEK_VELOCITY: 1 / 30,
  ATTACK_DISTANCE: 2,
};

export const GAME = {
  NUMBER_OF_INIT_SPAWNS: 20,
  NUMBER_OF_MAX_SPAWNS: 40,
  INIT_ANIMATION_DURATION: 500,
};

export const COLLISION_GROUP = {
  CORONA: 1,
  TILES: 4,
  BODY: 8,
  CHEST: 16,
  BAT: 32,
};

export const MAP = {
  NUMBER_OF_BBOX: 43,
};
